Import("outerEnv")
Import("notebooklib")

env = outerEnv.Clone()

env.AppendUnique(FRAMEWORKS=["Cocoa", "RegexKit", "Python"])
env.AppendUnique(CPPPATH=[".", "#Notebook"])
files = Glob("*.m")

NBPython = env.LoadableModule("NBPython", files, LIBS=[notebooklib])

NBPythonBundle = env.Bundle("NBPython", creator="NOTB", resources=["python.png"], frameworks=[], dylibs=[], suffix=".bundle", hasPkgInfo=False)

Depends(NBPythonBundle, NBPython)

Return("NBPythonBundle")