Import("outerEnv")
Import("notebooklib")
Import("liblua")

env = outerEnv.Clone()

env.AppendUnique(FRAMEWORKS=["Cocoa", "RegexKit"])
env.AppendUnique(CPPPATH=[".", "#Notebook"])
files = Glob("*.m")

NBLua = env.LoadableModule("NBLua", files, LIBS=[notebooklib, liblua])

NBLuaBundle = env.Bundle("NBLua", creator="NOTB", resources=["lua.png"], frameworks=[], dylibs=[], suffix=".bundle", hasPkgInfo=False)

Depends(NBLuaBundle, NBLua)

Return("NBLuaBundle")